<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robomuse">

    <!--................................ XACRO CONSTANTS .............................. -->

    <xacro:property name="chassis_mass" value="70"/>
    <xacro:property name="chassis_length" value="0.9"/>
    <xacro:property name="chassis_width" value="0.64"/>
    <xacro:property name="chassis_height" value="0.19"/>

    <xacro:property name="traction_wheel_mass" value="1"/>
    <xacro:property name="traction_wheel_base" value="0.88"/>
    <xacro:property name="traction_max_wheel_torque" value="20000"/>
    <xacro:property name="traction_wheel_friction" value="5.0"/>

    <xacro:property name="trolley_wheel_mass" value="0.1"/>
    <xacro:property name="trolley_track_width" value="0.54"/>
    <xacro:property name="trolley_wheel_friction" value="0.0"/>
    <xacro:property name="trolley_wheel_radius" value="0.06"/>
    <!-- a small constant -->
    <xacro:property name="eps" value="0.002"/>

    <xacro:property name="traction_wheel_radius" value="0.1"/>
    <xacro:property name="traction_wheel_width" value="0.05"/>
    <xacro:property name="traction_track_width" value="0.6"/>

    <xacro:property name="two_d_lidar_update_rate" value="30"/>
    <xacro:property name="two_d_lidar_sample_size" value="361"/>
    <xacro:property name="two_d_lidar_min_angle" value="0"/>
    <xacro:property name="two_d_lidar_max_angle" value="360"/>
    <xacro:property name="two_d_lidar_min_range" value="0.55"/>
    <xacro:property name="two_d_lidar_max_range" value="16"/>


    <xacro:arg name="robot_namespace" default=""/>
    <xacro:arg name="wheel_odom_topic" default="odom" />
    <xacro:arg name="two_d_lidar_enabled" default="false" />
    <xacro:arg name="publish_wheel_odom_tf" default="true" />
    <xacro:arg name="ground_truth_frame" default="map"/>
    <xacro:arg name="sim_gazebo" default="false" />
    <xacro:arg name="sim_gz" default="false" />
    <xacro:arg name="odometry_source" default="world" />

    <xacro:property name="odometry_source" value="$(arg odometry_source)"/>

    <!-- ............................... LOAD MACROS ................................. -->

    <xacro:include filename="$(find robomuse)/urdf/macros.xacro"/>

    <xacro:if value="$(arg sim_gazebo)">
        <xacro:include filename="$(find robomuse)/urdf/gazebo.xacro"/>
    </xacro:if>

    <xacro:if value="$(arg sim_gz)">
        <xacro:include filename="$(find robomuse)/urdf/gz.xacro"/>
    </xacro:if>

    <!-- ................................ BASE LINK .................................. -->
    <link name="base_footprint"/>

    <link name="base_link"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0 ${chassis_height/2 + traction_wheel_radius}" rpy="0 0 0.0" />
    </joint>

    <link name="chassis_link">

        <collision>
            <origin xyz="0 0 -0.05" rpy="0 0 0" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 -0.205" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find robomuse)/meshes/robomuse62.dae" scale="1 1 1"/>
            </geometry>
        </visual>

        <inertial>
            <mass value="${chassis_mass}" />
            <xacro:box_inertia m="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z = "${chassis_height}"/>
        </inertial>

    </link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="0.0 0 0" rpy="0 0 0.0" />
    </joint>

    <!-- ................................ WHEELS ..................................... -->

    <xacro:trolley_wheel cardinality="front" dexterity="left" origin_x="${chassis_length/2}" origin_y="${trolley_track_width/3}" origin_z="-${trolley_wheel_radius+chassis_height/2}"/>
    <xacro:trolley_wheel cardinality="front" dexterity="right" origin_x="${chassis_length/2}" origin_y="-${trolley_track_width/3}" origin_z="-${trolley_wheel_radius+chassis_height/2}"/>

    <xacro:trolley_wheel cardinality="back" dexterity="left" origin_x="-${chassis_length/2}" origin_y="${trolley_track_width/2}" origin_z="-${trolley_wheel_radius+chassis_height/2}"/>
    <xacro:trolley_wheel cardinality="back" dexterity="right" origin_x="-${chassis_length/2}" origin_y="-${trolley_track_width/2}" origin_z="-${trolley_wheel_radius+chassis_height/2}"/>

    <xacro:traction_wheel cardinality="middle" dexterity="left" origin_x="0" origin_y="${traction_track_width/2}" origin_z="-${chassis_height/2+2*trolley_wheel_radius+eps-traction_wheel_radius}"/>
    <xacro:traction_wheel cardinality="middle" dexterity="right" origin_x="0" origin_y="-${traction_track_width/2}" origin_z="-${chassis_height/2+2*trolley_wheel_radius+eps-traction_wheel_radius}"/>

    <!-- ............................. 2D LIDAR ........................................ -->

    <xacro:if value="$(arg two_d_lidar_enabled)">

        <link name="two_d_lidar">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="0.06" radius="0.075"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="0.1"/>
                <xacro:cylinder_inertia m="0.1" r="0.075" h="0.06"/>
            </inertial>
        </link>

        <joint name="two_d_lidar_joint" type="fixed">
            <parent link="base_link"/>
            <child link="two_d_lidar"/>
            <origin xyz="0.35 0 -0.025" rpy="0 0 0" />
        </joint>

        <gazebo reference="two_d_lidar">
            <material>Gazebo/White</material>
        </gazebo>

    </xacro:if>

    

</robot>
